apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: frontend
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        tier: frontend
    spec:
      containers:
      - name: cart
        image: balumpcs007/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports:
        - name: liveness-port
          containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: frontend
spec:
  selector:
    project: roboshop
    component: cart
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080 # target port
      targetPort: 8080 # container port
