apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: roboshop 
          - name: RABBITMQ_DEFAULT_PASS
            value: roboshop123
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # target port
      targetPort: 5672 # container port
